### ISSUE TITLE
Incompatible native module: serialport

### ISSUE THREAD

**Issue by leo3linbeck** [spark/spark-dev#107]
Loaded spark-dev module, got the following in the Incompatible Package window:

Error message: Cannot find module '/Users/leo3/.atom/packages/spark-dev/node_modules/serialport/build/serialport/v1.6.3/Release/atom-shell-v0.22.3-darwin-x64/serialport.node'

Particle menu is blank (I'm guess because Spark Dev 0.0.25 stops loading upon error).

OS: Mac OSX 10.10.5
Hardware: Mac Pro (Mid 2012)
Atom: 1.0.7

**Comment by suda** [comment]
Yeah, this is caused by [bug in apm](https://github.com/atom/apm/pull/345). You can solve it by following steps 4 and 5 from [Linux instructions](https://github.com/spark/spark-dev#linux)
