### ISSUE TITLE
Failed to load the spark-dev package

### ISSUE THREAD

**Issue by cbnatrix** [spark/spark-dev#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [spark-dev](https://github.com/spark/spark-dev) package, v0.0.25

### Stack Trace

Failed to load the spark-dev package

```
At 'progress.less' wasn't found in /Users/john/.atom/packages/spark-dev/styles/spark-dev.less:6:0

LessError: 'progress.less' wasn't found
  at /Users/john/.atom/packages/spark-dev/styles/spark-dev.less:6:0
```

### Commands

```
     -2:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ABC-notation, v1.0.1
language-arduino, v0.3.1
language-elixir, v0.5.2
language-erlang, v3.0.0
language-lua, v0.9.4
remote-edit, v1.8.15
spark-dev, v0.0.25
unity-ui, v2.1.0
vim-mode, v0.59.0

# Dev
No dev packages
```

**Comment by suda** [comment]
@cbnatrix it has been fixed in f212a09 but won't be released until 0.0.26. In the meantime I recommend switching UI Theme to i.e. Atom Light.
