### ISSUE TITLE
Uncaught Error when compiling/uploading

### ISSUE THREAD

**Issue by ineil** [spark/spark-dev#117]
This error always appears when attempting to compile/upload on Mac OSX 10.10.5.
![sparkdev](https://cloud.githubusercontent.com/assets/486018/10183872/a06913ea-672c-11e5-9c41-c9a7bad20662.jpg)

Note that I use Atom separately at its most recent version. I also noticed that in the Atom release history a similar sounding ENOENT issue is described as being resolved on Windows for version 1.0.17.

**Comment by suda** [comment]
@ineil this is a generic version when trying to access non existent dir. Could you try opening just one directory (I see you have opened `config` and `particle`)?

**Comment by suda** [comment]
This should be fixed in [v0.0.28](https://github.com/spark/spark-dev/releases/tag/v0.0.28).
