### ISSUE TITLE
Save needed before compile?

### ISSUE THREAD

**Issue by tgmcnaughton** [spark/spark-dev#119]
Is it just me?  In the atom editor, clicking "Compile and show errors if any" doesn't compile what's seen in the current tab , but the last saved version of the file. I can understand allowing the option of not automatically saving prior to each compile, but this is not the default behavior I'd expect.  Also - clicking on an error opens up a new black untitled pane rather than taking me to the line number in the source.

**Comment by suda** [comment]
Hi @tgmcnaughton! Thanks for filing this issue. It was actually raised in #31. It's different behavior than in Build IDE so it'll definitely be unified.
