### ISSUE TITLE
Empty errors array causes crash

### ISSUE THREAD

**Issue by suda** [spark/spark-dev#123]
See: https://github.com/spark/particle-dev-cloud-functions/issues/2

**Comment by Aditya90** [comment]
I am also running into this issue. How am I supposed to resolve this?

**Comment by suda** [comment]
@Aditya90 are you using standalone Particle Dev App or Atom and `particle-dev` package?

**Comment by Aditya90** [comment]
I am using the standalone particle dev PC application. Also, I am unsure about the "particle-dev" package you are talking about. I am coming back to an older project of mine in the hopes of completing it - https://github.com/Aditya90/GardenWatering-Firmware. I am trying to compile master but am running into problems. It used to compile at one point.

**Comment by suda** [comment]
@Aditya90 by `particle-dev` package I mean using [Atom](https://atom.io/) and installing [`particle-dev` package in Atom](https://atom.io/packages/particle-dev). The package contains latest development including bugfixes.
