### ISSUE TITLE
spark-dev install failure

### ISSUE THREAD

**Issue by matt-gordonboyworks** [spark/spark-dev#130]
Atom 1.2.1, OS X El Capitan 10.11.1, there's a failure to install (no red bug indicating the option to rebuild modules.)  Path  /private/var/folders/mv/p6jbtd3j20g3_dtfv4vz2jph0000gn/T/apm-install-dir-1151017-5672-1wuu87o/npm-debug.log does not exist.

[spark-dev install error.txt](https://github.com/spark/spark-dev/files/37040/spark-dev.install.error.txt)

**Comment by suda** [comment]
Thx Matt, will look into this.

**Comment by tlorens** [comment]
Fresh install/reinstall of OS X. - Atom 1.2.1 / OS X Yosemite (10.10.5).  I've got the same problem.  Just to rule out El Capitan (10.11.1).

**Comment by tlorens** [comment]
Appears to be a problem after Atom 1.1.0.  Installed 1.2.x (bets included) and continues to fail.

**Comment by drankinn** [comment]
it's working good for me now. 
Thanks!
