### ISSUE TITLE
Atom can't install spark-dev: error mentions serialport?

### ISSUE THREAD

**Issue by rahji** [spark/spark-dev#134]
Every other package in the instructions installed without problems but spark-dev gives this error:

Installing “spark-dev@0.0.31” failed

[errors.txt](https://github.com/spark/spark-dev/files/71435/errors.txt)

**Comment by drankinn** [comment]
I'm seeing the same thing.  
Running ubuntu 15.10

**Comment by suda** [comment]
@rahji & @drankinn can you check again now? I updated dependent package which should fix the problem.

**Comment by olafveerman** [comment]
Did a fresh install and I'm not experiencing any issues anymore. Thanks @suda
