### ISSUE TITLE
"Compile in cloud" treats include paths differently than web IDE, breaks most of the library code examples

### ISSUE THREAD

**Issue by DaveCasey** [spark/spark-dev#140]
Most library example code uses includes of the form: #include "LibraryName/LibraryName.h"

This is also the form that the web IDE uses when it adds a library for you:
// This #include statement was automatically added by the Particle IDE.
#include "OneWire/OneWire.h"

The dev environment requires you to strip the foldername from the include:
#include "OneWire.h"
will compile.
#include "OneWire/OneWire.h"
will fail with the following error:

![image](https://cloud.githubusercontent.com/assets/185453/14367844/3fb73cdc-fce8-11e5-9be9-e69a8d5953c5.png)

Regardless of whether you use this directory structure:
![image](https://cloud.githubusercontent.com/assets/185453/14367881/6aa324ba-fce8-11e5-857c-f7182d4aad85.png)

or this directory structure:
![image](https://cloud.githubusercontent.com/assets/185453/14367933/a2c31bac-fce8-11e5-92fe-78f1a1912d88.png)

**Comment by DaveCasey** [comment]
Note that the following block from the spark-dallas-temperature library's spark-dallas-temperature.h
must also be updated in order to get Dev's "Compile in the cloud" to succeed.

#elif defined(SPARK) or defined(STM32F10X_MD)
    #include "application.h"
    #include "../OneWire/OneWire.h"
#endif

must be changed to:
#elif defined(SPARK) or defined(STM32F10X_MD)
    #include "application.h"
    #include "OneWire.h"
#endif


Asking users to modify libraries that they don't own seems like a bad idea....

**Comment by suda** [comment]
Hi Dave, this is [an open issue](https://github.com/spark/spark-dev/issues/71) with our dev tools, API and compile server but we'll keep doing incremental fixes so all the parts to fix this problem will be in place.
