### ISSUE TITLE
'No such file or directory' error when using hpp file extension for C++ header files

### ISSUE THREAD

**Issue by adam1658** [spark/spark-dev#141]
If I name a header file with an 'hpp' extension, compilation fails with 'No such file or directory'.
The same happens when working with template classes, and I name an implementation header file with 'tpp' as the extension.

This is frustrating, as atom will treat an 'h' file as c, while an 'hpp' or 'tpp' file as c++.
Is this a limitation of Particle Dev, or the cloud compiler?

**Comment by suda** [comment]
Hi @adam1658, Dev currently includes only `.h`, `.ino`, `.cpp` and `.c` files. [Support for .ignore/.include files when compiling](https://github.com/spark/spark-dev/issues/39) will fix it though. Until then you should still be able to compile using CLI.
