### ISSUE TITLE
Unsaved files in project should ask to be saved when compiling?

### ISSUE THREAD

**Issue by technobly** [spark/spark-dev#31]
Currently in the Web IDE, if you make changes and press Verify... it saves the files automatically and then compiles.

In Spark Dev, it will only try to read the current state of the files saved on your hard drive and compile those.  This is a common "gotcha" with stand alone IDE's where when you make a change and recompile without saving first you don't see the change, and you spend a considerable amount of time trying to debug why the change you can see in the editor is not found in your device.  It could be solved by automatically saving all open files when attempting to Verify or Flash.  If the files are unsaved it should probably ask you to save them.

---
Related to this: 

~~There is a feature that I had planned to ask for that is supported on the Arduino IDE, where you can make changes to a file and compile and flash the unsaved changes to your arduino.  This is useful for quickly editing the examples without having to find a place to save them, or to copy paste some code from the web to try much in the same way.  Sometimes you just want to try something without saving it and cluttering up your hard drive with one more set of files.~~

~~If the way unsaved files was handled was something more like it makes a copy of all files in your project and all open unsaved files to a temporary location whenever you press Verify or Flash, it would be able to compile unsaved or saved files transparently.~~
Moved to #45 

---

Settings for all of this would make it powerful and fully in the user's control as well.  For example you could have settings for Autosaving or not, Compiling unsaved changes or not, Ask to save unsaved files when compiling or flashing... or just save them automatically.

**Comment by embedded-creations** [comment]
+1 for this issue (just got bit by it).

**Comment by uchobby** [comment]
+1 on this issue.  I do not see this as an enhancement it should be listed as a bug to get priority attention. Many if not all developers will suffer from this issue!  The online IDE even saves before compile.

Auto-save is expected in a modern IDE and if it was a config option I'd make sure it's default to active.
