### ISSUE TITLE
Program shows: App code is invalid every compile

### ISSUE THREAD

**Issue by mihirt** [spark/spark-dev#44]
See issue with pictures here: https://community.spark.io/t/spark-dev-app-code-was-invalid/8289
essentially, whenever I try to compile a .ino file, the compiler says "App code is invalid" and doesn't allow me to compile. Any reasons as to why it won't compile? Spark core is powered and connected to the same network as the computer running spark dev.

**Comment by MrRocketman** [comment]
I also see this problem when I tried to have a git repo with my code in it. Looks like it's trying to compile the git repo info.

**Comment by suda** [comment]
@MrRocketman 2b84505bee5ef74d403c6e92900f11abbe65dda2 should fix issue with .git dir

@DanDawson unfortunately we don't support spaces in filenames on compile server level. We recommend using camel case or dashes instead. I'll add more descriptive error for this case though.

**Comment by DanDawson** [comment]
Thanks @suda and I should have known spaces wouldn't have been supported (pretty standard) so I think a more descriptive error message will help out other users too, thanks!

**Comment by tkelestemur** [comment]
I encountered with same problem. I put my code as shown in below image. 
After I copied my code folder (driveOneMotor) to desktop and re-tried, It worked fine.
My problem could because of other arduino code .dropbox initial file in the folder.

![screen shot 2015-01-09 at 14 06 24](https://cloud.githubusercontent.com/assets/5513783/5679467/d20f5eb6-9808-11e4-9824-29605edc86c5.png)

**Comment by cmatheus** [comment]
I ran into this problem and fixed it by removing a .gitignore file.

**Comment by tmelvin** [comment]
.git still had the "App code invalid." error.  (v. 0.0.20) I just put all my code in a sub directory of my git repo.

**Comment by suda** [comment]
This should be now fixed in [0.0.21](https://github.com/spark/spark-dev/releases/tag/v0.0.21)
