### ISSUE TITLE
Can't compile, having errors.

### ISSUE THREAD

**Issue by darklow** [spark/spark-dev#63]
Windows 8, spark-dev v0.0.19. Spark windows driver installed.
Spark dev is authenticated to cloud.
Spark core is successfully compiling through web IDE.
Spark core is connected to spark-dev and selected and slowly pulsating neon in status bar.

I tried simplest `blink.ino` and as soon as i push Compile i got following errors and nothing happens further:
```
Uncaught TypeError: Cannot read property '0' of undefined c:\Program Files (x86)\Spark Dev\resources\app\node_modules\spark-dev\node_modules\when\lib\decorators\unhandledRejection.js:100
Uncaught Error: Cannot find module 'request' module.js:346
```

Tried starting from scratch and deleting `.spark-dev` directory from windows user home. 
But it didn't helped.
Any ideas?

**Comment by suda** [comment]
@darklow & @gfarrell could you test latest (0.0.20) version?

Also: there may be errors when you have .git dir in your project (it has been fixed but not released yet) or [spaces in filenames](https://github.com/spark/spark-dev/issues/44#issuecomment-68892982).

**Comment by darklow** [comment]
I just tested in v0.0.20 and now compile works . 
Thank you.

**Comment by suda** [comment]
@darklow great to hear that!
