### ISSUE TITLE
spark-dev overwrites `atom` and `apm` commands on launch

### ISSUE THREAD

**Issue by gfarrell** [spark/spark-dev#65]
Launching spark-dev (v0.0.19, not sure about earlier versions) causes the `atom` and `apm` commands (in `/usr/local/bin` on OSX) to be overwritten to point to spark-dev, instead of my Atom installation.

I use Atom for most of my normal development work, so this is extremely frustrating.

**Comment by suda** [comment]
This has been fixed in #57 and will be available in next release planned for next week.
