### ISSUE TITLE
.git file causing compilation issue

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-dev#68]
All ".xxxx" files are not required to be sent to the cloud for compilation and this would work as a blacklist unless the user explicitly wants to include the files.

1.) **.git** is part of the listed ignored names under preference but resulted in a compilation error

2.) .gitignore was part of my folder and it caused the same issue

3.) We should either blacklist all the ".git" or check why the ignored names are not respected by the dev IDE

**Comment by suda** [comment]
Yeah it [has been fixed](https://github.com/spark/spark-dev/issues/63#issuecomment-69000914) but not yet released. We should push 0.0.21 soon.
