### ISSUE TITLE
Firmware Upload RGB led problem when used RGB.control(true);

### ISSUE THREAD

**Issue by hallard** [spark/spark-dev#70]
Hi there,
Not really an issue, just to let you know that when user take control of RGB LED with  
`RGB.control(true);`  
Then when we upload new firmware, during the 1st phase of firmware transfer (the upload) take control of the LED just for blinking (ie it blink only the led)
So if the led was off at this precise time we don't see anything, else the LED start blinking with the color it had just before upload started instead of magenta.

Oh, forgot to mention, it seems it rely only with spark-dev, not tried with WEB IDE

**Comment by m-mcgowan** [comment]
@hallard  Thanks for the report. This is a known issue with the firmware, and is being tracked here - https://github.com/spark/firmware/issues/362.

**Comment by suda** [comment]
I think you should
