### ISSUE TITLE
Confusion Error Message

### ISSUE THREAD

**Issue by dljamo** [spark/spark-dev#76]
![screen shot 2015-03-09 at 6 38 15 pm](https://cloud.githubusercontent.com/assets/8630235/6567852/af81f8b6-c68b-11e4-8454-6e5e8af35041.png)

A customer was confused by this error message, which in all likelihood is a result of him trying to claim it before getting the Core online. It might be good to ask the customer "Is your Core online?".

**Comment by suda** [comment]
You're right, this is confusing. There is an idea of creating step by step claiming UI in Dev which should be much clearer than using Identify/Setup WiFi/Claim options separately.
