### ISSUE TITLE
"Show cloud variables and functions" menu item still showing up

### ISSUE THREAD

**Issue by jenesaisdiq** [spark/spark-dev#78]
Doesn't work, and as I recall has been deprecated for the separate ones... but still shows up. Fix it.
https://www.dropbox.com/s/le6bkoqy244cdiz/Screenshot%202015-04-19%2012.13.34.png?dl=0

**Comment by suda** [comment]
This should be now fixed in [0.0.21](https://github.com/spark/spark-dev/releases/tag/v0.0.21)
