### ISSUE TITLE
Bundle tool-bar-main with Particle Dev

### ISSUE THREAD

**Issue by ScruffR** [spark/spark-dev#81]
When I try to flash my firmware by use of the onboard console pane, I do see the gray "input your command here" message, but once I start entering text the input box goes blank and I can't see what I type.
But when I press <keyb>ENTER</keyb> the correct command is executed.

**Comment by suda** [comment]
@ScruffR could you try the latest 0.0.23?

**Comment by ScruffR** [comment]
That's a funny way to solve the problem ;-)
In 0.0.23 the console "button" seems to be gone.

**Comment by suda** [comment]
@ScruffR could you share a screenshot?

**Comment by ScruffR** [comment]
That's how it looks on my machine
![particledev0023](https://cloud.githubusercontent.com/assets/6604878/7690514/82f7b6b8-fdb4-11e4-8d50-2ecade768ae3.png)

**Comment by suda** [comment]
You see these errors when you click `Flash` in upper left corner?

**Comment by ScruffR** [comment]
No, these appear when I open the the Dev Tools pane, close it and open it again.
But these errors don't seem to have anything to do with the "missing" console button ;-)

**Comment by suda** [comment]
Do you mean this one: https://www.dropbox.com/s/neiim6a5jntfhx6/Screenshot%202015-05-19%2012.07.34.png?dl=0 ? Because it's part of [tool-bar-main](https://atom.io/packages/tool-bar-main) which isn't bundled with Dev.

**Comment by ScruffR** [comment]
Yes, that's the one, but up to v0.0.21 it appeard on the bottom status bar of my Windows "Spark Dev" without any furter ado ;-)
How can I add it now to 0.0.23?

**Comment by suda** [comment]
Currently installing 3rd party packages is blocked by #80 but is to be fixed this sprint.

**Comment by ScruffR** [comment]
OK, then I'll wait for that fix - thanks!
