### ISSUE TITLE
[WebIDE] error box stuck below

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-dev#98]
Once a compilation error is detected, hitting verify again caused this:

<img width="1265" alt="screen shot 2015-07-12 at 10 10 23" src="https://cloud.githubusercontent.com/assets/6760914/8636050/e407916e-287d-11e5-80a1-2ef34146e775.png">

**Comment by suda** [comment]
@kennethlimcp can you confirm it's fixed?
