### ISSUE TITLE
Weird errors with .c files, .cpp files work fine

### ISSUE THREAD

**Issue by Techjar** [spark/spark-dev#99]
I get the error `type_traits: No such file or directory` whenever I try to compile anything, and I'm not sure if this is a legitimate issue or if I've just missed something non-obvious. It gives the mostly meaningless line number `.:31:23`. My code is just empty setup() and loop() methods, and does have `#include "application.h"`.

More info: I restarted Particle Dev and now I'm getting a plethora of dumb errors referring to the file `.`, including but not limited to `expected identifier or '(' before string constant` and `unknown type name '_off_t'`.

Another edit: Okay, now I'm really confused. Renaming the file to `.cpp` instead of `.c` fixes the errors. Would someone mind explaining this?

**Comment by kennethlimcp** [comment]
i believe only `.ino`, `.h`, `,cpp` files are allowed

**Comment by suda** [comment]
@Techjar could you zip the project dir and share it?

**Comment by Techjar** [comment]
There's nothing particularly unique about it, but sure.
http://owncloud.techjargaming.com/public.php?service=files&t=FjP4SKdvlZBxrJC

**Comment by kennethlimcp** [comment]
IMO `.c` is not supported

**Comment by suda** [comment]
@Techjar when I renamed `main.c` to `application.cpp` it compiles. Sorry the default filename isn't specified in docs. Will add it right now :)

**Comment by Techjar** [comment]
Does it need to be `application.cpp` or will `main.cpp` work as well?

**Comment by suda** [comment]
Any `.cpp` should work. Naming your code `.c` suggests the compiler your code is in C but the [firmware](https://github.com/spark/firmware) is written in C++ and the `application.h` header uses a lot of its features (like `extern "C"`). This is why you can't mix those.

**Comment by Techjar** [comment]
Ah. Weird, because `.c` used to work in older versions.
